version: "3.8"

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: blue-green-deployment-nginx
    ports:
      - "8080:80"    # public entrypoint for grader and browser
    depends_on:
      - app_blue
      - app_green
    networks:
      - app_net

  app_blue:
    image: ${BLUE_IMAGE}
    container_name: app_blue
    environment:
      - APP_POOL=blue
      - RELEASE_ID=${RELEASE_ID_BLUE}
      - PORT=8080
    ports:
      - "8081:8080"  # grader calls /chaos/* on host:8081
    networks:
      - app_net

  app_green:
    image: ${GREEN_IMAGE}
    container_name: app_green
    environment:
      - APP_POOL=green
      - RELEASE_ID=${RELEASE_ID_GREEN}
      - PORT=8080
    ports:
      - "8082:8080"  # grader calls /chaos/* on host:8082
    networks:
      - app_net
    networks:
      app_net:
        driver: bridge