FROM nginx:stable-alpine

RUN apk add --no-cache gettext


COPY nginx.conf.template /etc/nginx/templates/nginx.conf.template


COPY nginx-entrypoint.sh /usr/local/bin/nginx-entrypoint.sh


RUN chmod +x /usr/local/bin/nginx-entrypoint.sh

EXPOSE 80
ENTRYPOINT ["/usr/local/bin/nginx-entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
